#!/bin/bash

if [[ $# -eq 0 ]] || [[ $# -eq 1 ]] || [[ $1 == "--help" ]] || [[ $1 == "-h" ]] || [[ $1 == "-help" ]] || [[ $2 == "--help" ]] || [[ $2 == "-h" ]] || [[ $2 == "-help" ]]; then
  echo "Usage: $0 [INFILE] [OUTFILE]"
  echo "Description: Strips metadata from media files"
  exit
fi

if [[ ! -s $1 ]]; then
  echo "File $1 doesn't exist or is empty."
  exit
fi

if [[ -s $2 ]]; then
  echo "File $2 already exists."
  exit
fi

ffmpeg -i "$1" -map_metadata -1 -c:v copy -c:a copy -fflags +bitexact -flags:v +bitexact -flags:a +bitexact "$2" 2> /dev/null

